docker/Caturday/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls', namespace='landing')),
    path('polls/', include('catpolls.urls', namespace='catpolls')),
    path('blogs/', include('catblogs.urls', namespace='catblogs')),
    path('thoth/', include('omnipotenthoth.urls', namespace='thoth')),
    path('accounts/', include('accounts.urls', namespace='reg_auth')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docker/accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_v

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/',  views.get_profile, name='get_profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),

    path('login/', auth_v.LoginView.as_view(), name='login'),
    path('logout/', auth_v.LogoutView.as_view(), name='logout'),

    path('password-reset/', auth_v.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_v.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_v.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/', auth_v.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('password-change/', auth_v.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_v.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

docker/accounts/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    info = models.TextField(max_length=300, blank=True)

    def __str__(self):
        return f"Profile of user {self.user}"

docker/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.utils.translation import gettext_lazy as _


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'info')
        labels = {'info': _("Motto")}
        widgets = {'date_of_birth': forms.SelectDateWidget(
            empty_label=("Year", "Month", "Day"),
            years=range(2020, 1950, -1))}

docker/accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Profile
from .forms import UserRegistrationForm, UserEditForm, ProfileEditForm


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request, 'accounts/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'user_form': user_form})


@login_required
def get_profile(request):
    profile_detail = get_object_or_404(Profile, user=request.user)
    return render(request, 'accounts/profile.html', {'profile_detail': profile_detail})


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
        return get_profile(request)
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
        return render(request, 'accounts/edit.html',
                      {'user_form': user_form,
                       'profile_form': profile_form})

docker/accounts/templates/accounts/edit.html
{% extends "accounts/main.html" %}

{% block content %}
    <div class="mess">
        <h2>Edition of profile</h2>
        <p>You can edit your profile using the following form:</p>
        <form action="." method="post">
            <table>
                <tr><td>{{ user_form.first_name.label_tag }}
                    <br>{{ user_form.first_name }}</td></tr>
                <tr><td>{{ user_form.last_name.label_tag }}
                    <br>{{ user_form.last_name }}</td></tr>
                <tr><td>{{ user_form.email.label_tag }}
                    <br>{{ user_form.email }}</td></tr>
                <tr><td>{{ profile_form.date_of_birth.label_tag }}
                    <br>{{ profile_form.date_of_birth }}</td></tr>
                <tr><td>{{ profile_form.info.label_tag }}
                    <br>{{ profile_form.info }}</td></tr>
            </table>
            {% csrf_token %}
            <div class="but-wrap">
                <input class="button" type="submit" value="Save changes">
            </div>
        </form>
    </div>
{% endblock %}

docker/accounts/templates/accounts/main.html
{% load static %}

<html lang="en-us" >
<head>
    <title>Caturday</title>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/main.css' %}">
    <link rel="icon" type="image" href="{% static 'accounts/images/icon1.jpg' %}">
</head>
<body>
<div class="body-wrapper">
    <div id="header">
        <div class="branding">
          <a href="/">Every day is Caturday</a>
        </div>
        <div class="logout">
            {% if user.is_authenticated %}
            <a class="log-but" href="{% url 'accounts:logout' %}"><div class="butout">Log out</div></a>
            {% endif %}
        </div>
    </div>
    <div id="main">
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div id="footer"></div>
</div>
</body>
</html>

docker/accounts/templates/accounts/profile.html
{% extends "accounts/main.html" %}

{% block content %}
    <div class="mess">
        <h2>{{ profile_detail }}</h2>
        <p>Welcome to your profile!</p>
        <table>
            <tr><td>First name:</td>
                <td>{{ user.first_name }}</td></tr>
            <tr><td>Last name:</td>
                <td>{{ user.last_name }}</td></tr>
            <tr><td>E-mail:</td>
                <td>{{ user.email }}</td></tr>
            <tr><td>Joined:</td>
                <td>{{ user.date_joined }}</td></tr>
            <tr><td>Birthday date:</td>
                <td>{% if profile_detail.date_of_birth %}
                        {{ profile_detail.date_of_birth }}
                    {% endif %}</td></tr>
            <tr><td>Motto:</td>
                <td>{{ profile_detail.info }}</td></tr>
        </table>
        <div class="but-wrap2">
            <a class="e-but" href="{% url 'accounts:edit_profile' %}"><div class="button">Edit profile</div></a>
        </div>
        <div class="but-wrap">
            <a class="e-but" href="{% url 'accounts:password_change' %}"><div class="button">Change password</div></a>
        </div>
    </div>
{% endblock %}

docker/accounts/templates/accounts/register.html
{% extends "accounts/main.html" %}

{% block content %}
    <h2>Create an account</h2>
    <div class="mess">
        <p>Please, sign up using the following form:</p>
    </div>
    <form action="." method="post">
        <div class="mess">
            {% if user_form.errors %}
                {{ user_form.username.errors }}
                {{ user_form.first_name.errors }}
                {{ user_form.email.errors }}
                {{ user_form.password.errors }}
                {{ user_form.password2.errors }}
            {% endif %}
        </div>
        <table>
            <tr>
                <td colspan="2">Username should contain {{ user_form.username.help_text|safe|linebreaksbr }}<br>
                With '*' are marked required fields.</td>
            </tr>
            <tr>
                <td>* {{ user_form.username.label_tag }}</td>
                <td>{{ user_form.username }}</td>
            </tr>
            <tr>
                <td>{{ user_form.first_name.label_tag }}</td>
                <td>{{ user_form.first_name }}</td>
            </tr>
            <tr>
                <td>{{ user_form.last_name.label_tag }}</td>
                <td>{{ user_form.last_name }}</td>
            </tr>
            <tr>
                <td>* {{ user_form.email.label_tag }}</td>
                <td>{{ user_form.email }}</td>
            </tr>
            <tr>
                <td>* {{ user_form.password.label_tag }}</td>
                <td>{{ user_form.password }}</td>
            </tr>
            <tr>
                <td>* {{ user_form.password2.label_tag }}</td>
                <td>{{ user_form.password2 }}</td>
            </tr>
        </table>
        {% csrf_token %}
        <div class="but-wrap">
            <input class="button" type="submit" value="Create account" />
        </div>
    </form>
{% endblock %}

docker/accounts/templates/accounts/register_done.html
{% extends "accounts/main.html" %}

{% block content %}
    <h2>Welcome,
        {% if new_user.first_name %}
            {{ new_user.first_name }}!
        {% else %}
            {{ new_user.username }}!
        {% endif %}
    </h2>
    <p><br>Your account has been successfully created.</p>
    <div class="but-wrap">
        <a class="log-but" href="{% url 'accounts:login' %}"><div class="button">Log in</div></a>
    </div>
{% endblock %}