docker/Caturday/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls', namespace='landing')),
    path('polls/', include('catpolls.urls', namespace='catpolls')),
    path('blogs/', include('catblogs.urls', namespace='catblogs')),
    path('thoth/', include('omnipotenthoth.urls', namespace='thoth')),
    path('accounts/', include('accounts.urls', namespace='reg_auth')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docker/accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_v

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/',  views.get_profile, name='get_profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),

    path('login/', auth_v.LoginView.as_view(), name='login'),
    path('logout/', auth_v.LogoutView.as_view(), name='logout'),

    path('password-reset/', auth_v.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_v.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_v.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/', auth_v.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('password-change/', auth_v.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_v.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

docker/catblogs/urls.py
from django.urls import path, include
from . import views

app_name = 'catblogs'

urlpatterns = [
    path('', views.PostListView.as_view(), name='catpost_list'),
    path('catpost/', include([
        path('new/', views.catpost_new, name='catpost_new'),
        path('my_posts/', views.MyPostListView.as_view(), name='catpost_my_posts'),
        path('recent/', views.RecentPostListView.as_view(), name='catpost_recent'),
        path('archive/', views.ArchivePostListView.as_view(), name='catpost_archive'),
        path('short_stories/', views.ShortPostListView.as_view(), name='catpost_short'),
        path('articles/', views.ArticlePostListView.as_view(), name='catpost_article'),
        path('<int:pk>/', views.catpost_detail, name='catpost_detail'),
        path('<int:pk>/edit/', views.catpost_edit, name='catpost_edit'),
    ])),
]

docker/catblogs/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class CatPost(models.Model):
    catauthor = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  on_delete=models.SET_DEFAULT,
                                  default=19)
    catitle = models.CharField(max_length=200)
    catext = models.TextField()
    creation_date = models.DateTimeField(default=timezone.now)
    publication_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.publication_date = timezone.now()
        self.save()

    def __str__(self):
        return self.catitle

docker/catblogs/forms.py
from django import forms
from .models import CatPost


class CatPostForm(forms.ModelForm):

    class Meta:
        model = CatPost
        fields = ['catitle', 'catext']

docker/catblogs/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
import datetime
from django.utils import timezone
from django.views import generic
from .models import CatPost
from .forms import CatPostForm


"""def catpost_list(request):
    catposts = CatPost.objects.filter(
        publication_date__lte=timezone.now()
        ).order_by('publication_date')
    return render(request, 'catblogs/catpost_list.html', 
                  {'catposts': catposts})"""


class PostListView(generic.ListView):
    template_name = 'catblogs/catpost_list.html'
    context_object_name = 'catposts'
    model = CatPost
    paginate_by = 3

    def get_queryset(self):
        return CatPost.objects.filter(
            publication_date__lte=timezone.now()
        ).order_by('publication_date')


class RecentPostListView(generic.ListView):
    template_name = 'catblogs/catpost_list.html'
    context_object_name = 'catposts'

    def get_queryset(self):
        return CatPost.objects.filter(
            publication_date__gte=timezone.now() - datetime.timedelta(days=30)
        ).order_by('publication_date')


class ArchivePostListView(generic.ListView):
    template_name = 'catblogs/catpost_list.html'
    context_object_name = 'catposts'
    model = CatPost
    paginate_by = 3

    def get_queryset(self):
        return CatPost.objects.filter(
            publication_date__lte=timezone.now() - datetime.timedelta(days=365)
        ).order_by('publication_date')


class ShortPostListView(generic.ListView):
    template_name = 'catblogs/catpost_list.html'
    context_object_name = 'catposts'

    def get_queryset(self):
        return CatPost.objects.extra(
            where=["LENGTH(catext) < 300"]
        ).order_by('publication_date')


class ArticlePostListView(generic.ListView):
    template_name = 'catblogs/catpost_list.html'
    context_object_name = 'catposts'
    model = CatPost
    paginate_by = 3

    def get_queryset(self):
        return CatPost.objects.filter(
            catext__contains='article'
        ).order_by('publication_date')


class MyPostListView(generic.ListView):
    template_name = 'catblogs/catpost_list.html'
    context_object_name = 'catposts'
    model = CatPost
    paginate_by = 3

    def get_queryset(self):
        return CatPost.objects.filter(
            catauthor=self.request.user
        ).order_by('publication_date')


def catpost_detail(request, pk):
    catpost = get_object_or_404(CatPost, pk=pk)
    return render(request, 'catblogs/catpost_detail.html', {'catpost': catpost})


@login_required
def catpost_new(request):
    if request.method == "POST":
        catform = CatPostForm(request.POST)
        if catform.is_valid():
            catpost = catform.save(commit=False)
            catpost.catauthor = request.user
            catpost.publication_date = timezone.now()
            catpost.save()
            return redirect('catblogs:catpost_detail', pk=catpost.pk)
    else:
        catform = CatPostForm()
    return render(request, 'catblogs/catpost_edit.html', {'catform': catform})


def catpost_edit(request, pk):
    catpost = get_object_or_404(CatPost, pk=pk)
    if request.method == 'POST':
        catform = CatPostForm(request.POST, instance=catpost)
        if catform.is_valid():
            catpost = catform.save(commit=False)
            catpost.catauthor = request.user
            catpost.publication_date = timezone.now()
            catpost.save()
            return redirect('catblogs:catpost_detail', pk=catpost.pk)
    else:
        catform = CatPostForm(instance=catpost)
    return render(request, 'catblogs/catpost_edit.html', {'catform': catform})

docker/catblogs/templates/catblogs/base.html
{% load static %}

<html>
<head>
    <title>Blogs</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'catblogs/css/style.css' %}">
    <link rel="icon" type="image" href="{% static 'catblogs/images/icon1.jpg' %}">
</head>
<body>
<div class="body-wrapper">
    <header class="header">
        <div class="header-wrapper">
            <div class="logo">
                <a href="/">Caturday Blogs</a>
            </div>

            <div class="login">
                {% if not user.is_authenticated %}
                <div class="reglink"><a href="{% url 'accounts:register' %}">Registration</a></div>
                <a class="log-but" href="{% url 'accounts:login' %}?next={{request.path}}"><div class="button">Log in</div></a>
                {% elif user.is_authenticated %}
                <div class="user"><a href="{% url 'accounts:get_profile' %}">{{ user.get_username }}</a></div>
                <a class="log-but" href="{% url 'accounts:logout' %}"><div class="button">Log out</div></a>
                {% endif %}
            </div>
        </div>
    </header>
    <div class="content">
        <div class="main">
            {% block content %}
            {% endblock %}
        </div>
        <div class="sidebar">
            <nav class="nav">
                <ul class="nav-ul">
                    <a href="{% url 'catblogs:catpost_new' %}"><li>Create new</li></a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'catblogs:catpost_my_posts' %}"><li>My posts</li></a>
                    {% endif %}
                    <a href="/blogs"><li>All publications</li></a>
                    <a href="{% url 'catblogs:catpost_recent' %}"><li>Recent publications</li></a>
                    <a href="{% url 'catblogs:catpost_short' %}"><li>Short stories</li></a>
                    <a href="{% url 'catblogs:catpost_article' %}"><li>Serious articles</li></a>
                    <a href="{% url 'catblogs:catpost_archive' %}"><li>Archive of publications</li></a>
                </ul>
            </nav>
        </div>
    </div>
    <footer class="footer">
        <div class="footer-content">
            <p>© 2021 Made by Chameleon Leonard ~^o.o^~</p>
        </div>
    </footer>
</div>
</body>
</html>

docker/catblogs/templates/catblogs/catpost_detail.html
{% extends 'catblogs/base.html' %}
{% load static %}

{% block content %}
    <div class="post">
        <h2>{{ catpost.catitle }}</h2>
        <p>{{ catpost.catext|linebreaksbr }}</p>
        <div class="container">
            {% if user.is_authenticated and request.user == catpost.catauthor %}
            <div class="edit">
                <a href="{% url 'catblogs:catpost_edit' pk=catpost.pk %}">
                    <img src="{% static 'catblogs/images/img-pencil.png' %}"> edit post
                </a>
            </div>
            {% endif %}
            {% if catpost.publication_date %}
            <div class="date">
                <p>&nbsp;{{ catpost.catauthor }}. {{ catpost.publication_date }}</p>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}

docker/catblogs/templates/catblogs/catpost_edit.html
{% extends 'catblogs/base.html' %}

{% block content %}
    <h2>Edit post</h2>
    <div class="form">
        <form method="POST" class="post-form">{% csrf_token %}
            <div class="edit-title">
                <p>Edit title: {{ catform.catitle }}</p>
            </div>
            <div class="edit-text">
                <p>Edit text: {{ catform.catext }}</p>
            </div>
            <div class="edit-button">
                <button type="submit">Publish</button>
            </div>
        </form>
    </div>
{% endblock %}

docker/catblogs/templates/catblogs/catpost_list.html
{% extends 'catblogs/base.html' %}

{% block content %}
    {% if catposts %}
        <h1>Famous Cats tell their stories</h1>
        {% for catpost in catposts %}
            <div class="post">
                <h2><a href="{% url 'catblogs:catpost_detail' pk=catpost.pk %}">{{ catpost.catitle }}</a></h2>
                <p class="post-text">{{ catpost.catext|truncatewords:90|linebreaksbr }}</p>
                <p class="auth-date">Author: {{ catpost.catauthor }}. Published: {{ catpost.publication_date }} </p>
                <hr>
            </div>
        {% endfor %}
        {% if is_paginated %}
            <div class="paginator">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a class="pag-a" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    {% else %}
        <div class="post">
            <p class="post-text">Unfortunately, there is no posts in this category.</p>
        </div>
    {% endif %}
{% endblock %}