docker/Caturday/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls', namespace='landing')),
    path('polls/', include('catpolls.urls', namespace='catpolls')),
    path('blogs/', include('catblogs.urls', namespace='catblogs')),
    path('thoth/', include('omnipotenthoth.urls', namespace='thoth')),
    path('accounts/', include('accounts.urls', namespace='reg_auth')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docker/catblogs/urls.py
from django.urls import path, include
from . import views

app_name = 'catblogs'

urlpatterns = [
    path('', views.PostListView.as_view(), name='catpost_list'),
    path('catpost/', include([
        path('new/', views.catpost_new, name='catpost_new'),
        path('my_posts/', views.MyPostListView.as_view(), name='catpost_my_posts'),
        path('recent/', views.RecentPostListView.as_view(), name='catpost_recent'),
        path('archive/', views.ArchivePostListView.as_view(), name='catpost_archive'),
        path('short_stories/', views.ShortPostListView.as_view(), name='catpost_short'),
        path('articles/', views.ArticlePostListView.as_view(), name='catpost_article'),
        path('<int:pk>/', views.catpost_detail, name='catpost_detail'),
        path('<int:pk>/edit/', views.catpost_edit, name='catpost_edit'),
    ])),
]

docker/homepage/urls.py
from django.urls import path
from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.index, name='index')
]

docker/omnipotenthoth/urls.py
from django.urls import path
from . import views

app_name = 'thoth'

urlpatterns = [
    path('', views.tip_start, name='tip_start'),
    path('tip/', views.tip_next, name="tip_next"),
]

docker/homepage/models.py
from django.db import models

# Create your models here.

docker/homepage/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'homepage/index.html')

docker/homepage/templates/homepage/index.html
{% load static %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Caturday</title>
    <meta name="description" content="Site created for practice while studying">
    <meta name="author" content="Chameleon Leonard">
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}">
    <link rel="icon" type="image" href="{% static 'homepage/images/icon1.jpg' %}">
</head>
<body>
    <header class="header">
        <div class="overlay">
            <h1 class="header-title"><small>Every day is<br></small><big>Caturday</big></h1>
        </div>
    </header>

    <section class="content">
        <div class="card">
            <a href="{% url 'thoth:tip_start' %}">
                <div class="card-block">
                    <img src="{% static 'homepage/images/seamless_back3.jpg' %}" class="card-image">
                    <h3 class="card-title">Thoth</h3>
                    <p class="card-text">The power of omnipotent Thoth: he randomly gives you some advice,
                        succinct statement or ask rhetorical question for thinking about.</p>
                </div>
            </a>
        </div>

        <div class="card">
            <a href="{% url 'catpolls:index' %}">
                <div class="card-block">
                    <img src="{% static 'homepage/images/seamless_back2.jpg' %}" class="card-image">
                    <h3 class="card-title">Polls</h3>
                    <p class="card-text">Here we do not shy about expressing our thoughts.
                        Real chance to be involved in common catlife - taking part in votes.</p>
                </div>
            </a>
        </div>

        <div class="card">
            <a href="{% url 'catblogs:catpost_list' %}">
                <div class="card-block">
                    <img src="{% static 'homepage/images/seamless_back1.jpg' %}" class="card-image">
                    <h3 class="card-title">Blogs</h3>
                    <p class="card-text">Incredible stories from cool guys about their totaly inimitable lifes.
                        Let's just enjoy fairy tales or true stories.</p>
                </div>
            </a>
        </div>
    </section>

    <footer class="footer">
        <h4 class="footer-author">My goal is to inspire you for good deeds. Meow! ~^o.o^~</h4>
    </footer>
</body>
</html>