docker/Caturday/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls', namespace='landing')),
    path('polls/', include('catpolls.urls', namespace='catpolls')),
    path('blogs/', include('catblogs.urls', namespace='catblogs')),
    path('thoth/', include('omnipotenthoth.urls', namespace='thoth')),
    path('accounts/', include('accounts.urls', namespace='reg_auth')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docker/accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_v

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/',  views.get_profile, name='get_profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),

    path('login/', auth_v.LoginView.as_view(), name='login'),
    path('logout/', auth_v.LogoutView.as_view(), name='logout'),

    path('password-reset/', auth_v.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_v.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_v.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/', auth_v.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('password-change/', auth_v.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_v.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

docker/catpolls/urls.py
from django.urls import path
from . import views

app_name = 'catpolls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('popular/', views.PopularView.as_view(), name='popular'),
    path('random/', views.RandomView, name='random'),
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('<int:pk>/results/', views.ResultsView.as_view(), name="results"),
    path('<int:catuestion_id>/vote/', views.vote, name="vote"),
]

docker/catpolls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Catuestion(models.Model):
    catuestion_text = models.CharField(max_length=200)
    publication_date = models.DateTimeField('date published')
    catuestion_image = models.ImageField(upload_to='polls-img/', default='polls-img/img23.jpg')

    def __str__(self):
        return self.catuestion_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.publication_date <= now

    was_published_recently.admin_order_field = 'publication_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Cachoice(models.Model):
    catuestion = models.ForeignKey(Catuestion, on_delete=models.CASCADE)
    cachoice_text = models.CharField(max_length=200)
    cavotes = models.IntegerField(default=0)

    def __str__(self):
        return self.cachoice_text

docker/catpolls/forms.py
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import Catuestion, Cachoice


class CatuestionForm(forms.ModelForm):

    class Meta:
        model = Catuestion
        fields = ['catuestion_text', 'catuestion_image']
        labels = {'catuestion_text': _('Question'),
                  'catuestion_image': _('Image')}


class CahoiceForm(forms.ModelForm):

    class Meta:
        model = Cachoice
        extra = 3
        fields = ['cachoice_text']
        labels = {'cachoice_text': _('answer')}
        widgets = {
            'choice': forms.TextInput(attrs={'type': 'hidden',
                                             'id': 'payload',
                                             'class': 'form-control',
                                             'required': True})}


PollChoiceFormSet = forms.modelformset_factory(Cachoice,
                                               form=CahoiceForm,
                                               extra=2,
                                               can_delete=False)

docker/catpolls/views.py
from django.db.models import Sum
from django.db.models import Max
from random import randint

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from . import forms
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Catuestion, Cachoice


class IndexView(generic.ListView):
    template_name = 'catpolls/list.html'
    context_object_name = 'latest_catuestion_list'
    model = Catuestion
    paginate_by = 3

    def get_queryset(self):
        return Catuestion.objects.filter(
            publication_date__lte=timezone.now()
        ).order_by('-publication_date')


class PopularView(generic.ListView):
    template_name = 'catpolls/popular.html'
    context_object_name = 'popular_catuestion_list'

    def get_queryset(self):
        return Catuestion.objects.annotate(
            sum_votes=Sum('cachoice__cavotes')
        ).order_by('-sum_votes')[:5]


def rand_tip():
    max_id = Catuestion.objects.all().aggregate(max_id=Max("id"))['max_id']
    while True:
        pk = randint(1, max_id)
        if Catuestion.objects.filter(pk=pk):
            return pk


def RandomView(request):
    catuestion = get_object_or_404(Catuestion, pk=rand_tip())
    return render(request, 'catpolls/detail.html', {'catuestion': catuestion})


class DetailView(generic.DetailView):
    model = Catuestion
    template_name = 'catpolls/detail.html'

    def get_queryset(self):
        return Catuestion.objects.filter(publication_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Catuestion
    template_name = 'catpolls/results.html'


def vote(request, catuestion_id):
    question = get_object_or_404(Catuestion, pk=catuestion_id)
    try:
        selected_cachoice = question.cachoice_set.get(pk=request.POST['cachoice'])
    except (KeyError, Cachoice.DoesNotExist):
        return render(request, 'catpolls/detail.html', {
            'catuestion': question,
            'error_message': "You did not select a choice.",
            })
    else:
        selected_cachoice.cavotes += 1
        selected_cachoice.save()
    return HttpResponseRedirect(reverse('catpolls:results', args=(question.id,)))

docker/catpolls/templates/catpolls/create.html
{% extends 'catpolls/index.html' %}
{% load static %}

{% block content %}
    <h1>{{ catuestion.catuestion_text }}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form method="POST">
    {% csrf_token %}
    <div class="">
        <table>
            {{ form.as_table }}
        </table>
    </div>

    <div class="">
        <p>{{ CreateChoice.cachoice_text }}</p>
        <p>{{ PollChoiceFormSet }}</p>
    </div>

    <div class="">
        <input class="button" type="submit" value="Publish" />
    </div>

    </form>
{% endblock %}

docker/catpolls/templates/catpolls/detail.html
{% extends 'catpolls/index.html' %}
{% load static %}

{% block content %}
    <div class="image">
        <img class="img" src="{{ catuestion.catuestion_image.url }}">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    </div>

    <div class="question">
        <p>{{ catuestion.catuestion_text }}</p>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    </div>

    <div class="voting">
        <form action="{% url 'catpolls:vote' catuestion.id %}" method="post">
            {% csrf_token %}
            {% for cachoice in catuestion.cachoice_set.all %}
                <div class="choice">
                    <input type="radio" name="cachoice" id="cachoice{{ forloop.counter }}" value="{{ cachoice.id }}" />
                    <label for="cachoice{{ forloop.counter }}">{{ cachoice.cachoice_text }}</label><br />
                </div>
            {% endfor %}
            <div class="vote-button">
                <button type="submit">Vote</button>
            </div>
        </form>
    </div>
{% endblock %}

docker/catpolls/templates/catpolls/index.html
{% load static %}

<html>
<head>
    <title>Polls</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'catpolls/css/style.css' %}">
    <link rel="icon" type="image" href="{% static 'catpolls/images/icon1.jpg' %}">
</head>
<body>
<div class="body-wrapper">
    <header class="header">
        <div class="header-wrapper">
            <div class="logo">
                <a href="/">Caturday Polls</a>
            </div>

            <div class="nav-wrapper">
                <nav class="nav">
                    <ul class="nav-ul">
                        <a href="{% url 'catpolls:popular' %}"><li>Popular polls</li></a>
                        <a href="/polls"><li>All polls</li></a>
                        <a href="{% url 'catpolls:random' %}"><li>Random poll</li></a>
                    </ul>
                </nav>
            </div>

            <div class="login-wrapper">
                {% if not user.is_authenticated %}
                <div class="reglink"><a href="{% url 'accounts:register' %}">Registration</a></div>
                <a class="log-but" href="{% url 'accounts:login' %}?next={{request.path}}"><div class="button">Log in</div></a>
                {% elif user.is_authenticated %}
                <div class="user"><a href="{% url 'accounts:get_profile' %}">{{ user.get_username }}</a></div>
                <a class="log-but" href="{% url 'accounts:logout' %}"><div class="button">Log out</div></a>
                {% endif %}
            </div>
        </div>
    </header>

    <div class="content-wrapper">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="footer">
        <div class="footer-content">
            <p>© 2021 Made by Chameleon Leonard ~^o.o^~</p>
        </div>
    </footer>
</div>
</body>
</html>

docker/catpolls/templates/catpolls/list.html
{% extends 'catpolls/index.html' %}
{% load static %}

{% block content %}
    <div class="image">
        <img src="{% static 'catpolls/images/img20.jpg' %}">
    </div>

    <div class="question-list">
        {% if latest_catuestion_list %}
            <ul>
                {% for catuestion in latest_catuestion_list %}
                    <li><p class="li-block1"><a id="ques" href="{% url 'catpolls:detail' catuestion.id %}">{{ catuestion.catuestion_text }}</a></p>
                        <p class="li-block2"><a id="res" href="{% url 'catpolls:results' catuestion.id %}">See results</a></p></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </div>
    {% if is_paginated %}
        <div class="paginator">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a class="pag-a" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

docker/catpolls/templates/catpolls/popular.html
{% extends 'catpolls/index.html' %}
{% load static %}

{% block content %}
    <div class="image">
        <img src="{% static 'catpolls/images/img30.png' %}">
    </div>

    <div class="question-list">
        {% if popular_catuestion_list %}
            <ul>
                {% for catuestion in popular_catuestion_list %}
                    <li><p class="li-block1"><a id="ques" href="{% url 'catpolls:detail' catuestion.id %}">{{ catuestion.catuestion_text }}</a></p>
                        <p class="li-block2"><a id="res" href="{% url 'catpolls:results' catuestion.id %}">See results</a></p></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </div>
{% endblock %}

docker/catpolls/templates/catpolls/results.html
{% extends 'catpolls/index.html' %}
{% load static %}

{% block content %}
    <div class="question">
        <p>{{ catuestion.catuestion_text }}</p>
    </div>

    <div class="results">
        <ul>
            {% for cachoice in catuestion.cachoice_set.all %}
                <li>{{ cachoice.cachoice_text }} -- {{ cachoice.cavotes }} vote{{ cachioce.cavotes|pluralize }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="again">
        <a href="{% url 'catpolls:detail' catuestion.id %}">Vote again?</a>
    </div>
{% endblock %}